name: "Synthesize Terraform configuration"

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Synth"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run Terraform CDK
        run: npx cdktf-cli synth

      - name: Commit synthesized TF JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Synthesized Terraform configuration
          file_pattern: cdktf.out/