name: "Synthesize Terraform configuration"

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Synth"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.30
        with:
          terraformVersion: 1.5.3
          cdktfVersion: 0.17.1
          stackName: hc22-gitops-cdktf
          mode: synth-only
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit synthesized TF JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Synthesized Terraform configuration
          file_pattern: cdktf.out/